spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: partner-service
          uri: lb://partner-ws
          predicates:
            - Path=/partner/**
          filters:
            - AuthenticationFilter
        - id: contract-service
          uri: lb://contract-ws
          predicates:
            - Path=/contract/**
          filters:
            - AuthenticationFilter
        - id: identity-service
          uri: lb://identity-ws
          predicates:
             - Path=/auth/**
  security:
    jwt:
      secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw

server:
  port: 8080
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka