spring:
  application:
    name: "partner-ws"
  datasource:
    url: jdbc:h2:mem:partners
    driver-class-name: org.h2.Driver
    name: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
  h2:
    console.enabled: true

server:
  port: 0
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"


